title: InsideOut Sec
description: Offensive cybersecurity assessments, red teaming, and strategic resilience for high-value targets.
url: https://insideoutsec.io
logo: /assets/img/InsideOutSec_logo_def.avif
baseurl: "/"                       # root of the site

author:
  name: InsideOut Sec Team
  email: info@insideoutsec.io
  twitter: insideoutsec

social:
  name: InsideOut Sec
  links:
    - https://x.com/insideoutsec
    - https://www.linkedin.com/company/insideout-sec/

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# -------------------------------------------------
#  COLLECTIONS
# -------------------------------------------------
collections:
  casestudies:
    output: true                  # build a page for each file
    permalink: /casestudies/:title/

# -------------------------------------------------
#  DEFAULTS  (apply casestudy layout automatically)
# -------------------------------------------------
defaults:
  - scope:
      path: ""                    # entire repo
      type: casestudies
    values:
      layout: casestudy           # uses _layouts/casestudy.html

# -------------------------------------------------
#  SASS / BOOTSTRAP
# -------------------------------------------------
sass:
  load_paths:
    - assets/vendor               # contains bootstrap scss
  sass_dir: assets/css
  style: compressed
