- title: "Red Teaming"
  desc: "Advanced adversarial simulation to test your full cyber resilience."
  icon: "fas fa-user-secret"
- title: "Penetration Testing"
  desc: "Identify and validate vulnerabilities in real-world attack scenarios."
  icon: "fas fa-search"
- title: "Secure Architecture"
  desc: "Design cloud-native, hybrid, and zero-trust environments from scratch."
  icon: "fas fa-diagram-project"
- title: "Advisory & Compliance"
  desc: "Board-level consulting on risk, privacy, strategic alignment."
  icon: "fas fa-user-tie"